[Unit]
Wants = vrroom_with_volume.target

Conflicts = jack_disconnection@vrroom_volume.out_1\x2cjack_effects.in_1.service
Conflicts = jack_disconnection@vrroom_volume.out_2\x2cjack_effects.in_2.service
Wants = vrroom_with_volume.target

[Service]
Environment="SOURCE=4090"
