[Unit]
Description=Dante configuration enforcement — Ferrofish A32

Wants=dante-device-name@A32-107332.local.\x2ca32.target

Requires=dante-device-channel-name@a32\x2ctx\x2c17\x2cshelford-channel\x3a0db.target
Requires=dante-device-channel-name@a32\x2ctx\x2c18\x2cshelford-channel\x3aminus-6db.target
Requires=dante-device-channel-name@a32\x2ctx\x2c33\x2cmain-mix\x3aleft.target
Requires=dante-device-channel-name@a32\x2ctx\x2c34\x2cmain-mix\x3aright.target
Requires=dante-device-channel-name@a32\x2ctx\x2c49\x2cadat-1.target
Requires=dante-device-channel-name@a32\x2ctx\x2c50\x2cadat-2.target
Requires=dante-device-channel-name@a32\x2ctx\x2c51\x2cadat-3.target
Requires=dante-device-channel-name@a32\x2ctx\x2c52\x2cadat-4.target
Requires=dante-device-channel-name@a32\x2ctx\x2c53\x2cadat-5.target
Requires=dante-device-channel-name@a32\x2ctx\x2c54\x2cadat-6.target
Requires=dante-device-channel-name@a32\x2ctx\x2c55\x2cadat-7.target
Requires=dante-device-channel-name@a32\x2ctx\x2c56\x2cadat-8.target
Requires=dante-device-channel-name@a32\x2ctx\x2c57\x2cadat-25.target
Requires=dante-device-channel-name@a32\x2ctx\x2c58\x2cadat-26.target
Requires=dante-device-channel-name@a32\x2ctx\x2c59\x2cadat-27.target
Requires=dante-device-channel-name@a32\x2ctx\x2c60\x2cadat-28.target
Requires=dante-device-channel-name@a32\x2ctx\x2c61\x2cadat-29.target
Requires=dante-device-channel-name@a32\x2ctx\x2c62\x2cadat-30.target
Requires=dante-device-channel-name@a32\x2ctx\x2c63\x2cadat-31.target
Requires=dante-device-channel-name@a32\x2ctx\x2c64\x2cadat-32.target
Requires=dante-device-channel-name@a32\x2crx\x2c1\x2cmain-mix\x3aright.target
Requires=dante-device-channel-name@a32\x2crx\x2c2\x2cmain-mix\x3aleft.target
Requires=dante-device-channel-name@a32\x2crx\x2c3\x2cmusic\x3aleft.target
Requires=dante-device-channel-name@a32\x2crx\x2c4\x2cmusic\x3aright.target
Requires=dante-device-channel-name@a32\x2crx\x2c5\x2chdmi\x3aleft.target
Requires=dante-device-channel-name@a32\x2crx\x2c6\x2chdmi\x3aright.target
Requires=dante-device-channel-name@a32\x2crx\x2c7\x2cwireless-mic\x3a2-1.target
Requires=dante-device-channel-name@a32\x2crx\x2c8\x2cdesktop-mic\x3a1.target
Requires=dante-device-channel-name@a32\x2crx\x2c9\x2cbluetooth\x3aleft.target
Requires=dante-device-channel-name@a32\x2crx\x2c10\x2cbluetooth\x3aright.target
Requires=dante-device-channel-name@a32\x2crx\x2c11\x2cwindows\x3aleft.target
Requires=dante-device-channel-name@a32\x2crx\x2c12\x2cwindows\x3aright.target
Requires=dante-device-channel-name@a32\x2crx\x2c13\x2cmacbook\x3aleft.target
Requires=dante-device-channel-name@a32\x2crx\x2c14\x2cmacbook\x3aright.target
Requires=dante-device-channel-name@a32\x2crx\x2c15\x2cwireless-mic\x3a2-2.target
Requires=dante-device-channel-name@a32\x2crx\x2c16\x2cdesktop-mic\x3a2.target

Requires=dante-device-subscription@lx-dante\x2clinux-main\x3aright\x2ca32\x2cmain-mix\x3aright.target
Requires=dante-device-subscription@lx-dante\x2clinux-main\x3aleft\x2ca32\x2cmain-mix\x3aleft.target
Requires=dante-device-subscription@lx-dante\x2clinux-music\x3aleft\x2ca32\x2cmusic\x3aleft.target
Requires=dante-device-subscription@lx-dante\x2clinux-music\x3aright\x2ca32\x2cmusic\x3aright.target
Requires=dante-device-subscription@avio-bt-1\x2cbluetooth\x3aleft\x2ca32\x2cbluetooth\x3aleft.target
Requires=dante-device-subscription@avio-bt-1\x2cbluetooth\x3aright\x2ca32\x2cbluetooth\x3aright.target
Requires=dante-device-subscription@avio-usb-1\x2cwindows-gaming\x3aleft\x2ca32\x2cwindows\x3aleft.target
Requires=dante-device-subscription@avio-usb-1\x2cwindows-gaming\x3aright\x2ca32\x2cwindows\x3aright.target
Requires=dante-device-subscription@ad4d\x2c02\x2ca32\x2cwireless-mic\x3a2-1.target
Requires=dante-device-subscription@ad4d\x2c02\x2ca32\x2cwireless-mic\x3a2-2.target
