
[Unit]

After = ferrofish-a32.target
After = microphone.target
After = portico-5053-right.target
After = shure-p10t.target
Requires = ferrofish-a32.target
Requires = microphone.target
Requires = portico-5053-right.target
Requires = shure-p10t.target
