
[Unit]

After = ferrofish-a32.target
After = microphone.target
After = portico-5043-right.target
After = shure-p10t.target
Requires = ferrofish-a32.target
Requires = portico-5043-left.target
Requires = shure-p10t.target
