[Unit]
Description=Dante configuration enforcement — AVIO AES3-1 (VRRoom)

Wants=dante-device-name@AVIOAES3-53ef37.local.\x2cavio-aes3-1.target

Requires=dante-device-channel-name@avio-aes3-1\x2ctx\x2c1\x2cvrroom:left.target
Requires=dante-device-channel-name@avio-aes3-1\x2ctx\x2c2\x2cvrroom:right.target

Requires=dante-device-disconnection@avio-aes3-1\x2c01.target
Requires=dante-device-disconnection@avio-aes3-1\x2c02.target
