[Unit]
BindsTo = tv_speakers.target

[Service]
Environment="ALSA_DEVICE=hdmi:CARD=NVidia,DEV=0"
Environment="JACK_CLIENT_NAME=tv_speakers"
Environment="JACK_CLIENT_CHANNEL_COUNT=2"
Slice=audio-rt.slice
CPUAffinity=1-4
CPUSchedulingPolicy=fifo
CPUSchedulingPriority=90
