[Unit]

After = ecasound@jack.service
Description = ecasound %i effects
Requires = ecasound@jack.service
Requires = jackd.service
Wants = jack_connection@music_effects.out_1\x2csystem.playback_15.service
Wants = jack_connection@music_effects.out_2\x2csystem.playback_16.service

[Service]

Environment = TERM=xterm

# ExecStart = /usr/bin/zsh -ic "ecasound -C -f:f32_le,2,48000 -G:jack,%i_effects -a:1,2 -i jack,,in -o jack,,out -a:1 -elv2:http://calf.sourceforge.net/plugins/Compressor,0,1,0,0,0,0,0.155625,20,0.01,2000,1,1,0,0,1,1 -a:2 -elv2:http://calf.sourceforge.net/plugins/Limiter,0,1,0.587231,0,0,0,0,0,0,0,0,0.0625,0.1,1000,1,1,0,0.5,4"

# no-op
ExecStart = /usr/bin/ecasound -C -f:f32_le,2,48000 -G:jack,%i_effects -a:1 -i jack,,in -o jack,,out
