[Unit]

Description = ecasound %i effects

After = jackd.service
BindsTo = jackd.service
BindsTo = jack_effects.target

# After = dante_pcie_out.target
# Wants = dante_pcie_out.target

StopWhenUnneeded = yes

[Service]
Environment = JACK_NO_START_SERVER=1

TimeoutStartSec = 3s
Environment = TERM=xterm

CPUSchedulingResetOnFork = no

Environment = plugin=http://calf.sourceforge.net/plugins/SidechainCompressor

# /usr/lib/lv2/calf.lv2/SidechainCompressor.ttl

Environment = bypass=0
Environment = level_in=1
Environment = meter_in=0
Environment = meter_out=0
Environment = clip_in=0
Environment = clip_out=0
Environment = threshold=0.12
Environment = ratio=20
Environment = attack=0.01
Environment = release=2000
Environment = makeup=1
Environment = knee=8
Environment = detection=0
Environment = stereo_link=1
Environment = compression=1
Environment = sc_mode=0
Environment = f1_freq=250
Environment = f2_freq=4500
Environment = f1_level=1
Environment = f2_level=1
Environment = sc_listen=0
Environment = f1_active=1
Environment = f2_active=1
Environment = sc_route=0
Environment = sc_level=1
Environment = mix=1

# ExecStart = /usr/bin/zsh -ic "ecasound --no-server -C -f:f32_le,2,48000 -G:jack,%i_effects -a:1 -i jack,,in -o jack,,out -a:1 -elv2:$plugin,$bypass,$level_in,$meter_in,$meter_out,$clip_in,$clip_out,$threshold,$ratio,$attack,$release,$makeup,$knee,$detection,$stereo_link,$compression,9,$f1_freq,$f2_freq,$f1_level,$f2_level,$sc_listen,$f1_active,$f2_active,$sc_route,$sc_level,$mix"

# no-op
ExecStart = /usr/bin/ecasound --no-server -C -f:f32_le,2,48000 -G:jack,%i_effects -a:1 -i jack,,in -o jack,,out


[Install]
WantedBy=jack_clients.target
