
[Unit]

Description = Run Super Mario Bros 3 for NES
# Wants = super_mario_bros_3_notify.service

[Service]
ExecStart = /media/backup/software/gaming/mednafen/mednafen/src/mednafen /media/games/nintendo/nes/games/super_mario_bros_3.nes
ExecStartPost = -/usr/bin/sleep 0.25
ExecStartPost = -/usr/bin/wmctrl -a 'super mario bros 3'
