[Unit]

Description = Ferrofish A32 Dante
BindsTo = ferrofish-a32.target
StopWhenUnneeded = yes

[Service]

ExecStartPost = /usr/bin/zsh -ic "sleep 4.5"
ExecStartPost = /usr/bin/zsh -ic "until nc -vzw 1 'ferrofish-a32' 23 2>/dev/null; do sleep 0.5; done"

TimeoutStartSec = 25s
TimeoutStopSec = 10s
RestartSec = 10s
