
[Unit]

Before = microphone.service
Description = Microphone pre-amp
PartOf = shelford-channel.target

# PartOf = microphone.target
# Wants = microphone.service

StopWhenUnneeded = yes

[Service]

ExecStartPost = /usr/bin/sleep 3.0
RestartSec = 4s
TimeoutStartSec = 4s
