[Unit]

Conflicts = vrroom.target vrroom_with_volume.target
# Wants = tv_speakers.target

Requires = jack_disconnection@vrroom_volume.out_1\x2cjack_effects.in_1.service
Requires = jack_disconnection@vrroom_volume.out_2\x2cjack_effects.in_2.service

Conflicts = jack_connection@vrroom_volume.out_1\x2cjack_effects.in_1.service
Conflicts = jack_connection@vrroom_volume.out_2\x2cjack_effects.in_2.service

[Service]

Environment=SOURCE=
