[Unit]
Description = HDMI input 0: Linux workstation

Conflicts = hdmi_input@1.service hdmi_input@2.service hdmi_input@3.service
Conflicts = vrroom_audio.target
Wants = display-4k120@HDMI-0.service

Requires = jack_disconnection@vrroom_volume.out_1\x2clinux_main_volume.in_1.target
Requires = jack_disconnection@vrroom_volume.out_1\x2clinux_main_volume.in_2.target
Requires = jack_disconnection@vrroom_volume.out_2\x2clinux_main_volume.in_1.target
Requires = jack_disconnection@vrroom_volume.out_2\x2clinux_main_volume.in_2.target
After = jack_disconnection@vrroom_volume.out_1\x2clinux_main_volume.in_1.target
After = jack_disconnection@vrroom_volume.out_1\x2clinux_main_volume.in_2.target
After = jack_disconnection@vrroom_volume.out_2\x2clinux_main_volume.in_1.target
After = jack_disconnection@vrroom_volume.out_2\x2clinux_main_volume.in_2.target

Conflicts = jack_connection@vrroom_volume.out_1\x2clinux_main_volume.in_1.target
Conflicts = jack_connection@vrroom_volume.out_1\x2clinux_main_volume.in_2.target
Conflicts = jack_connection@vrroom_volume.out_2\x2clinux_main_volume.in_1.target
Conflicts = jack_connection@vrroom_volume.out_2\x2clinux_main_volume.in_2.target

[Service]

Environment=SOURCE=
TimeoutStartSec=45
ExecStartPost=%h/.local/bin/surface-hdmi-enforce --once --wait 30 --interval 1 HDMI-0
