[Unit]

# Before = microphone.service
# Description = Rupert Neve Shelford Channel (microphone pre-amp)
# BindsTo = shelford-channel.target

Description = Outlet 7
StopWhenUnneeded = yes

[Service]

# ExecStartPost = /usr/bin/zsh -ic "sleep 4.5"

TimeoutStartSec = 25s
TimeoutStopSec = 10s
RestartSec = 10s
