
[Unit]

StopWhenUnneeded = yes
PartOf = shure-ad4d.target

[Service]

ExecStartPost = /usr/bin/zsh -ic "sleep 4.5"
ExecStartPost = /usr/bin/zsh -ic "until nc -vzw 1 'shure-ad4d' 2202 2>/dev/null; do sleep 0.5; done"

TimeoutStartSec = 20s
TimeoutStopSec = 1s
RestartSec = 30s

