[Unit]

Description = PDU outlet 7: Neve Portico 5043 Right (stereo compressor)
StopWhenUnneeded = yes

[Service]

# ExecStartPost = /usr/bin/zsh -ic "sleep 4.5"

TimeoutStartSec = 25s
TimeoutStopSec = 10s
RestartSec = 10s
