
[Unit]

StopWhenUnneeded = yes
PartOf = shure-p10t.target

[Service]

ExecStartPost = /usr/bin/zsh -ic "sleep 4.5"
ExecStartPost = /usr/bin/zsh -ic "until nc -vzw 1 'shure-p10t' 2202 2>/dev/null; do sleep 0.5; done"
ExecStartPost = /usr/bin/zsh -ic '%h/.scripts/zsh/maybe_mute.zsh'

TimeoutStartSec = 10s
TimeoutStopSec = 1s
RestartSec = 30s
