[Unit]
Description=Dante configuration enforcement — Digigram LX-Dante PCIe card

Requires=dante-device-sample-rate@lx-dante\x2c48000.target
After=dante-device-sample-rate@lx-dante\x2c48000.target

Wants=dante-device-name@LX-DANTE-081258.local.\x2clx-dante.target

Requires=dante-device-channel-name@lx-dante\x2crx\x2c1\x2cwireless-mic:1.target
Requires=dante-device-channel-name@lx-dante\x2crx\x2c2\x2cwireless-mic:2.target
Requires=dante-device-channel-name@lx-dante\x2crx\x2c3\x2cshelford-channel:minus-6db.target
Requires=dante-device-channel-name@lx-dante\x2crx\x2c4\x2cshelford-channel:0dB.target
Requires=dante-device-channel-name@lx-dante\x2crx\x2c5\x2cdi-box:left.target
Requires=dante-device-channel-name@lx-dante\x2crx\x2c6\x2cdi-box:right.target
Requires=dante-device-channel-name@lx-dante\x2crx\x2c7\x2cwindows-gaming:left.target
Requires=dante-device-channel-name@lx-dante\x2crx\x2c8\x2cwindows-gaming:right.target
Requires=dante-device-channel-name@lx-dante\x2crx\x2c9\x2cdinet:left.target
Requires=dante-device-channel-name@lx-dante\x2crx\x2c10\x2cdinet:right.target
Requires=dante-device-channel-name@lx-dante\x2crx\x2c15\x2cvrroom:left.target
Requires=dante-device-channel-name@lx-dante\x2crx\x2c16\x2cvrroom:right.target
Requires=dante-device-channel-name@lx-dante\x2crx\x2c19\x2cadat:left.target
Requires=dante-device-channel-name@lx-dante\x2crx\x2c20\x2cadat:right.target
Requires=dante-device-channel-name@lx-dante\x2crx\x2c21\x2cbluetooth:left.target
Requires=dante-device-channel-name@lx-dante\x2crx\x2c22\x2cbluetooth:right.target

Requires=dante-device-channel-name@lx-dante\x2ctx\x2c11\x2clinux-main:left.target
Requires=dante-device-channel-name@lx-dante\x2ctx\x2c12\x2clinux-main:right.target
Requires=dante-device-channel-name@lx-dante\x2ctx\x2c13\x2cmic-mix:high.target
Requires=dante-device-channel-name@lx-dante\x2ctx\x2c14\x2cmic-mix:low.target
Requires=dante-device-channel-name@lx-dante\x2ctx\x2c15\x2clinux-music:left.target
Requires=dante-device-channel-name@lx-dante\x2ctx\x2c16\x2clinux-music:right.target

Requires=dante-device-subscription@ad4d\x2c01\x2clx-dante\x2cwireless-mic:1.target
Requires=dante-device-subscription@ad4d\x2c02\x2clx-dante\x2cwireless-mic:2.target
Requires=dante-device-subscription@a32\x2cshelford-channel\x3aminus-6db\x2clx-dante\x2cshelford-channel:minus-6db.target
Requires=dante-device-subscription@a32\x2cshelford-channel\x3a0db\x2clx-dante\x2cshelford-channel:0dB.target
Requires=dante-device-subscription@avio-usb-1\x2cwindows-gaming:left\x2clx-dante\x2cwindows-gaming:left.target
Requires=dante-device-subscription@avio-usb-1\x2cwindows-gaming:right\x2clx-dante\x2cwindows-gaming:right.target
Requires=dante-device-subscription@avio-aes3-1\x2cvrroom:left\x2clx-dante\x2cvrroom:left.target
Requires=dante-device-subscription@avio-aes3-1\x2cvrroom:right\x2clx-dante\x2cvrroom:right.target
Requires=dante-device-subscription@a32\x2cadat-1\x2clx-dante\x2cadat:left.target
Requires=dante-device-subscription@a32\x2cadat-2\x2clx-dante\x2cadat:right.target
Requires=dante-device-subscription@avio-bt-1\x2cbluetooth:left\x2clx-dante\x2cbluetooth:left.target
Requires=dante-device-subscription@avio-bt-1\x2cbluetooth:right\x2clx-dante\x2cbluetooth:right.target
