[Unit]
Description=Dante configuration enforcement — AVIO BT-1 (Bluetooth)

Wants=dante-device-name@AVIOBT-5279b6.local.\x2cavio-bt-1.target

Requires=dante-device-channel-name@avio-bt-1\x2crx\x2c1\x2cmic-mix.target

Requires=dante-device-channel-name@avio-bt-1\x2ctx\x2c1\x2cbluetooth:left.target
Requires=dante-device-channel-name@avio-bt-1\x2ctx\x2c2\x2cbluetooth:right.target

Requires=dante-device-subscription@lx-dante\x2cmic-mix\x3ahigh\x2cavio-bt-1\x2cmic-mix.target
