[Unit]
After=ferrofish-a32.target
After=microphone.target
After=portico-5043-left.target
Requires=ferrofish-a32.target
Requires=portico-5043-left.target

Requires=netaudio-shure-channel@00:0e:dd:20:9f:35\x2c1\x2crf_mute\x2cfalse.service
Requires=netaudio-shure-channel@00:0e:dd:20:9f:35\x2c1\x2caudio_in_line_level\x2ctrue.service
