[Unit]
Description=Dante configuration enforcement — AVIO USB work-macbook-1 (dynamic)

Requires=dante-device-channel-name@avio-usb-work-macbook-1\x2ctx\x2c1\x2cmacbook-work-1:left.target
Requires=dante-device-channel-name@avio-usb-work-macbook-1\x2ctx\x2c2\x2cmacbook-work-1:right.target
Requires=dante-device-channel-name@avio-usb-work-macbook-1\x2crx\x2c1\x2cmic-mix-1.target
Requires=dante-device-channel-name@avio-usb-work-macbook-1\x2crx\x2c2\x2cmic-mix-2.target

Requires=dante-device-subscription@avio-usb-work-macbook-1\x2cmacbook-work-1\x3aleft\x2clx-dante\x2cmacbook-work-1\x3aleft.target
Requires=dante-device-subscription@avio-usb-work-macbook-1\x2cmacbook-work-1\x3aright\x2clx-dante\x2cmacbook-work-1\x3aright.target

Requires=dante-device-channel-name@lx-dante\x2crx\x2c17\x2cmacbook-work-1:left.target
Requires=dante-device-channel-name@lx-dante\x2crx\x2c18\x2cmacbook-work-1:right.target

Requires=dante-device-subscription@lx-dante\x2cmic-mix\x3ahigh\x2cavio-usb-work-macbook-1\x2cmic-mix-1.target
Requires=dante-device-subscription@lx-dante\x2cmic-mix\x3ahigh\x2cavio-usb-work-macbook-1\x2cmic-mix-2.target
