
[Service]

Environment = YMPD_PORT=8095
# Environment = MPD_HOST=%t/mpd_stream/socket
 
# ExecStart = /usr/bin/zsh -ic "ympd -w $YMPD_PORT --host=$MPD_HOST --port='0'"
# ExecStart = /usr/bin/zsh -ic "ympd -w $YMPD_PORT --host=%t/mpd_stream/socket --port='0'"
