[Unit]
Description=Dante configuration enforcement — Shure AD4D wireless mic receiver

Wants=dante-device-name@AD4D-fd4e13.local.\x2cad4d.target

Requires=dante-device-channel-name@ad4d\x2crx\x2c1\x2crx-listen.target

Requires=dante-device-channel-name@ad4d\x2ctx\x2c1\x2c01.target
Requires=dante-device-channel-name@ad4d\x2ctx\x2c2\x2c02.target
